service: workout-app-backend

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  environment:
    DYNAMODB_WORKOUTS_TABLE: workouts
    DYNAMODB_EXERCISES_TABLE: exercises
    DYNAMODB_WORKOUT_EXERCISES_TABLE: workout_exercises

functions:
  registerUser:
    handler: bin/registerUser
    events:
      - http:
          path: register
          method: post

  loginUser:
    handler: bin/loginUser
    events:
      - http:
          path: login
          method: post

  getWorkout:
    handler: bin/getWorkout
    events:
      - http:
          path: workout/{id}
          method: get

resources:
  Resources:
    WorkoutsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: workouts
        AttributeDefinitions:
          - AttributeName: workout_id
            AttributeType: S
        KeySchema:
          - AttributeName: workout_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ExercisesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: exercises
        AttributeDefinitions:
          - AttributeName: exercise_id
            AttributeType: S
        KeySchema:
          - AttributeName: exercise_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    WorkoutExercisesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: workout_exercises
        AttributeDefinitions:
          - AttributeName: workout_id
            AttributeType: S
          - AttributeName: exercise_id
            AttributeType: S
        KeySchema:
          - AttributeName: workout_id
            KeyType: HASH
          - AttributeName: exercise_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1